# Generated by Django 4.1.7 on 2023-03-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_usertime_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
