# Generated by Django 4.1.7 on 2023-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usertime_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertime',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
