# Generated by Django 4.1.7 on 2023-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_usertime_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='generated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
