# Generated by Django 4.1.7 on 2023-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_usertime_generated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
