# Generated by Django 4.1.7 on 2023-05-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_sunday_time_in_morning_overload_usertime_monday_time_out_afternoon_overload_grad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='generated_time',
        ),
    ]
