# Generated by Django 4.1.7 on 2023-05-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_usertime_generated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='is_active',
        ),
    ]
